name: clean_architecture_course
description: Posts App with clean architecture


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  shared_preferences: ^2.0.15
  http: ^0.13.5
  # Functional Programming things
  dartz: ^0.10.1
  # Solve problem of Dependency Injection
  get_it: ^7.2.0
  # Remove APIs
  internet_connection_checker: ^0.0.1+4
  # Implement to hash code [Comparing]
  equatable: ^2.0.5
  hexcolor: ^2.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0



flutter:


  uses-material-design: true
